version: "3.9"

services:
  asterisk:
    build:
        context: ./asterisk
        dockerfile: Dockerfile
    ports:
      - "5060:5060"
      - "5060:5060/udp"
      - "8088:8088"
      - "10000-10010:10000-10010/udp"
      - "10000-10010:10000-10010"
    environment:
      - NAT_ADDRESS=192.168.1.18 # CHANGE WITH YOUR LOCAL IP ADDRESS

